//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Collections.Generic;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://lookup.dbpedia.org/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://lookup.dbpedia.org/", IsNullable=false)]
public partial class ArrayOfResult {
    
    private List<ArrayOfResultResult> itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Result")]
    public List<ArrayOfResultResult> Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://lookup.dbpedia.org/")]
public partial class ArrayOfResultResult {
    
    private string labelField;
    
    private string uRIField;
    
    private string descriptionField;
    
    private string templatesField;
    
    private string redirectsField;
    
    private string refcountField;
    
    private List<ArrayOfResultResultClassesClass> classesField;
    
    private List<ArrayOfResultResultCategoriesCategory> categoriesField;
    
    /// <remarks/>
    public string Label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
    
    /// <remarks/>
    public string URI {
        get {
            return this.uRIField;
        }
        set {
            this.uRIField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string Templates {
        get {
            return this.templatesField;
        }
        set {
            this.templatesField = value;
        }
    }
    
    /// <remarks/>
    public string Redirects {
        get {
            return this.redirectsField;
        }
        set {
            this.redirectsField = value;
        }
    }
    
    /// <remarks/>
    public string Refcount {
        get {
            return this.refcountField;
        }
        set {
            this.refcountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Class", typeof(ArrayOfResultResultClassesClass), IsNullable=false)]
    public List<ArrayOfResultResultClassesClass> Classes {
        get {
            return this.classesField;
        }
        set {
            this.classesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Category", typeof(ArrayOfResultResultCategoriesCategory), IsNullable=false)]
    public List<ArrayOfResultResultCategoriesCategory> Categories
    {
        get {
            return this.categoriesField;
        }
        set {
            this.categoriesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://lookup.dbpedia.org/")]
public partial class ArrayOfResultResultClassesClass {
    
    private string labelField;
    
    private string uRIField;
    
    /// <remarks/>
    public string Label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
    
    /// <remarks/>
    public string URI {
        get {
            return this.uRIField;
        }
        set {
            this.uRIField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://lookup.dbpedia.org/")]
public partial class ArrayOfResultResultCategoriesCategory {
    
    private string labelField;
    
    private string uRIField;
    
    /// <remarks/>
    public string Label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
    
    /// <remarks/>
    public string URI {
        get {
            return this.uRIField;
        }
        set {
            this.uRIField = value;
        }
    }
}
